# Generated by Django 5.0.4 on 2024-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
