# Generated by Django 5.0.4 on 2024-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=350)),
                ('qualification', models.CharField(max_length=50)),
                ('date_of_joining', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=10)),
                ('father_or_husband', models.CharField(max_length=80)),
                ('experience', models.CharField(max_length=10)),
            ],
        ),
    ]
