# Generated by Django 4.0.3 on 2024-07-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectmaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='questionbank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('Subjective', 'Subjective Question')], max_length=10)),
                ('question', models.CharField(max_length=3000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('option1', models.CharField(blank=True, max_length=200, null=True)),
                ('option2', models.CharField(blank=True, max_length=200, null=True)),
                ('option3', models.CharField(blank=True, max_length=200, null=True)),
                ('option4', models.CharField(blank=True, max_length=200, null=True)),
                ('solution', models.CharField(max_length=3000)),
                ('option_choices', models.CharField(choices=[('option1', 'Option1'), ('option2', 'Option2'), ('option3', 'Option3'), ('option4', 'Option4')], max_length=10, verbose_name='Option Type')),
                ('question_weightage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.subjectmaster')),
            ],
        ),
    ]
