# Generated by Django 4.0.3 on 2024-07-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_shortcut', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MainCaste_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincaste_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='motherTongue_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mothertongue_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nationality_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Religion_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion_name', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBoard_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='State_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_shortcut', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='StdClass_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.section_master')),
            ],
        ),
        migrations.CreateModel(
            name='SubCaste_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castesub_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tehsil_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehsil_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state_master')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=10)),
                ('std_first_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('photo', models.FileField(blank=True, null=True, upload_to='student_photos')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10, verbose_name='Option Type')),
                ('admission_date', models.DateField()),
                ('std_rollno', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('birth_place', models.TextField()),
                ('aadharnumber', models.BigIntegerField()),
                ('aadharcard', models.FileField(blank=True, null=True, upload_to='Student_aadharcards')),
                ('domicile', models.CharField(max_length=100)),
                ('ph_number_father', models.BigIntegerField()),
                ('ph_number_mother', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('local_address', models.TextField()),
                ('postal_address', models.TextField()),
                ('postal_zip_code', models.IntegerField()),
                ('father_occupation', models.CharField(max_length=50)),
                ('mother_occupation', models.CharField(max_length=50)),
                ('caste_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caste_main', to='student.maincaste_master')),
                ('caste_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caste_sub', to='student.subcaste_master')),
                ('mother_tongue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.mothertongue_master')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.nationality_master')),
                ('postal_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city_master')),
                ('postal_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state_master')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='religion', to='student.religion_master')),
                ('std_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='std_class', to='student.stdclass_master')),
                ('std_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='student.section_master')),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.tehsil_master')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousSchoolDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Udise_num', models.IntegerField()),
                ('school_name', models.CharField(max_length=255)),
                ('school_address', models.TextField()),
                ('school_zip_code', models.CharField(max_length=20)),
                ('school_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('grade_attended', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='pdfs')),
                ('school_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.schoolboard_master')),
                ('school_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city_master')),
                ('school_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state_master')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentpersonaldetails')),
                ('tehsil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.tehsil_master')),
            ],
        ),
        migrations.AddField(
            model_name='city_master',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state_master'),
        ),
    ]
