# Generated by Django 4.0.3 on 2024-06-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdclass_master',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.section_master'),
        ),
    ]
