# Generated by Django 4.0.3 on 2024-07-13 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdclass_master',
            name='section',
        ),
    ]
