# Generated by Django 4.0.3 on 2024-07-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_stdclass_master_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='motherTongue_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castesub_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nationality_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castesub_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBoard_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='studentpersonaldetails',
            old_name='std_last_name',
            new_name='domicile',
        ),
        migrations.RenameField(
            model_name='studentpersonaldetails',
            old_name='std_middle_name',
            new_name='father_name',
        ),
        migrations.RemoveField(
            model_name='stdclass_master',
            name='teacher',
        ),
        migrations.AddField(
            model_name='previousschooldetails',
            name='Udise_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='previousschooldetails',
            name='school_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city_master'),
        ),
        migrations.AlterField(
            model_name='previousschooldetails',
            name='school_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state_master'),
        ),
        migrations.AlterField(
            model_name='previousschooldetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentpersonaldetails'),
        ),
        migrations.AlterField(
            model_name='studentpersonaldetails',
            name='postal_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.city_master'),
        ),
        migrations.AlterField(
            model_name='studentpersonaldetails',
            name='postal_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state_master'),
        ),
        migrations.CreateModel(
            name='Tehsil_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehsil_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.state_master')),
            ],
        ),
        migrations.AddField(
            model_name='previousschooldetails',
            name='tehsil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.tehsil_master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='mother_tongue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.mothertongue_master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.nationality_master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentpersonaldetails',
            name='tehsil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.tehsil_master'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='previousschooldetails',
            name='school_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.schoolboard_master'),
        ),
    ]
